apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  name: nvidia-gpu-operator
  namespace: ngpu
spec:
  applicationRef:
    name: nvidia-gpu-operator
    version: v24.6.1
  namespace:
    create: true
    name: ngpu
  reconciliationInterval: 0s
  valuesBlock: |-
    daemonsets:
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      - key: workload
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"

    operator:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      - key: workload
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"

    node-feature-discovery:
      fullnameOverride: gpu-operator-node-feature-discovery
      worker:
        tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        - key: workload
          operator: "Equal"
          value: "gpu"
          effect: "NoSchedule"
