apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-webhook-service-account
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: centraldashboard
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-web-app-service-account
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: katib-controller
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: katib-ui
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-controller-manager
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-models-web-app
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meta-controller-service
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebook-controller-service-account
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: profiles-controller-service-account
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvcviewer-controller-manager
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tensorboard-controller-controller-manager
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tensorboards-web-app-service-account
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: training-operator
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volumes-web-app-service-account
  namespace: kubeflow
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod
  namespace: istio-system
imagePullSecrets:
- name: kf-docker-cred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authservice
  namespace: istio-system
imagePullSecrets:
- name: kf-docker-cred