apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  name: nginx
  namespace: nginx
spec:
  applicationRef:
    name: nginx
    version: 1.9.6
  namespace:
    create: true
    name: nginx
  reconciliationInterval: 0s
  valuesBlock: |-
    controller:
      replicaCount: 3
      service:
        annotations:
          # Required for Istio
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"